---
vmid: 1010
proxmox_host: 192.168.33.21
proxmox_node: semperis-nuc-1
template_id: 9001
vm_cores: 2
vm_memory: 4096
vm_disk: 80G
proxmox_vm_tags: "adfr"
domain_name: D1.lab
netbios_name: D1
role: "Forest Root PDC"