---
vmid: 2210
proxmox_host: 192.168.33.21
proxmox_node: semperis-nuc-1
template_id: 9001
vm_cores: 2
vm_memory: 4096
vm_disk: 80G
proxmox_vm_tags: "adfr"
domain_name: D22.D2.lab
netbios_name: D22
parent_domain: D2.lab
role: "Child Domain PDC"