---
# D1.lab Forest - Single Domain Configuration

# Domain Identity
domain_name: d1.lab
netbios_name: D1

# DNS Configuration
dns_servers_pre_promo:
  - 1.1.1.1
  - 1.0.0.1
dns_servers_post_promo:
  - 172.16.10.10  # D1-DC01
  - 172.16.10.11  # D1-DC02

# Domain Controller for credential references
domain_pdc_host: D1-DC01
