---
ansible_connection: ssh
ansible_user: blyons
ansible_ssh_private_key_file: "/root/.ssh/ansible_key"
ansible_python_interpreter: /usr/bin/python3
ansible_become: true
ansible_become_method: sudo
ansible_port: 22

# Explicitly disable password auth
ansible_ssh_common_args: "-o PreferredAuthentications=publickey -o PasswordAuthentication=no"
ansible_password: ""
ansible_ssh_password: ""